### ISSUE TITLE
CGP189 : [BUG] enroll course action is not redirecting to estore 

### ISSUE THREAD

**Issue by babanesma** [camelcasetechsd/certigate#189]

**Comment by ahmedReda1** [comment]
The problem was that each time we create a course event  which is supposed to be new option value for already existed product option .. it was creating new product option , set the new option value in it and enforce making it required .. so each time we need to enroll in specific course event it gets conflict for the empty required course event product option

**Comment by babanesma** [comment]
Move the change you have done in `public/estore/catalog/model/catalog/option.php` to a new function in the same class and revert the old function  , just for the sake of future updates . And refer to this function with a flag in the api call .
