### ISSUE TITLE
CGP73: Add upload option to image in WYSIWYG

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/certigate#73]
Image add button is there in WYSIWYG editor, but when when you click it you cannot upload image to server, but you can add image using URL only.

**Comment by babanesma** [comment]
1. http://local-certigate.com/bower_components/ckeditor/config.js?t=FB9E this url is missing while opening the upload tab 
2. Change `Send it to the Server` to `upload`

**Comment by babanesma** [comment]
- After uploading the image , can you redirect automatically to the Browse Server window to select the uploaded the image . Because right now after uploading the image there is nothing to say that my image is uploaded or how to include it the content .
- When clicking `Browse Server` , disable the layout ( sidebar and header bar )
