### ISSUE TITLE
CGP86: Course Entity change

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/certigate#86]
1- Divide the course entity into 2 main entities
    a. course entity
    b. course event
2- Course entity creation form contains:
    a. name
    b. brief
    c. time
    d. duration
    e. CIP ( Train of the Trainer checkbox )
    f. outlines

![course](https://cloud.githubusercontent.com/assets/8982139/13552752/3b2814a4-e378-11e5-93d2-e746d6778fba.png)

**Comment by lebaz20** [comment]
Update Course entity
- [x] Remove fields [exambook, users, ai, atp, studentsNo, capacity, endDate, startDate]
- [x] Remove setters/getters [exambook, users, ai, atp, studentsNo, capacity, endDate, startDate]
- [x] Update exchangeArray method to exclude removed fields
- [x] Add courseEvents [OneToMany field type] with required validation

Update User entity
- [x] Update courses field to hold courseEvents instead

Create CourseEvent entity
- [x] Add fields deleted from Course entity [exambook, users, ai, atp, studentsNo, capacity, endDate, startDate]
- [x] Add setters/ getters and validations for fields deleted from Course entity [exambook, users, ai, atp, studentsNo, capacity, endDate, startDate]
- [x] Add course [ManyToOne field type] with required validation
- [x] Add votes [OneToMany field type]
- [x] Update exchangeArray method to include all fields

Update Vote entity
- [x] Add courseEvent [ManyToOne field type] with required validation

Update ExamBook entity
- [x] Replace course with courseEvent [ManyToOne field type] with required validation

Update Course form
- [x] userId property is not needed anymore -> move to CourseEvent form
- [x] move removed fields to CourseEvent form [ai, atp, studentsNo, capacity, endDate, startDate]
- [x] Update label for duration field
- Replace status field and create button with three buttons 
  - [x] Create new fieldset for buttons
  - [x] Update page form to use new fieldset
  - [x] Check button value in data array while saving:
    - [x] value is 'save' and in create stage -> set status to inactive
    - [x] value is 'save' and in edit stage -> do not set status [keep old status]
    - [x] value is 'save and publish' -> set status to active
    - [x] value is 'unpublish' -> set status to inactive

Update Outline fieldset
- [x] Update label for duration field

Update BookExam form
- [x] Replace course with courseEvent [ManyToOne field type] with required validation
  - [x] course events per course should appear under course option group where course event details are displayed per each course event 

Update Course/Resource CRUD acl
- [x] Remove other than admin access to course/resource CRUD [coursesNew, coursesEdit, courses, coursesPending, courseEvaluations, newCourseEvaluation, editCourseEvaluation, resourcesListPerCourse, resourcesNewPerCours, resourcesEdit] in seeds and fixtures

Update Course model
- [x] move methods [validateForm, enrollCourse, leaveCourse, setCanEnroll, prepareInstructorCourses] to CourseEvent model

Update Exam model
- [x] update saveBookingRequest method to set courseEvent instead of course

Update Course create/edit actions
- [x] move validateOrganizationAccessControl check to CourseEvent create/edit actions
- [x] move validateForm check to CourseEvent create/edit actions
- [x] move setStudentsNo check to CourseEvent create action

Update Course index action
- [x] modify validateOrganizationAccessControl check to ignore organization check
- [x] remove filtration in case of training manager 

Update Course newEvaluation/editEvaluation actions
- [x] modify validateOrganizationAccessControl check to ignore organization check

Update Exam book action
- [x] modify validateOrganizationAccessControl check to ignore organization check

Update Resource edit/create/index/edit-recource action
- [x] modify validateOrganizationAccessControl check to ignore organization check

Update Course index view
- [x] Remove view changes link
- [x] Remove moved fields to course event

Update course seed
- [x] Remove extra fields [ai, atp, studentsNo, capacity, endDate, startDate] from course seed

Update course outlines form
- [x] Add five outlines by default and via add more button

**Comment by babanesma** [comment]
- when creating new course event ( /course-events/new/1 ) , omit the select box of the courses , make it hidden or get it from the url query
