### ISSUE TITLE
CGP88: Course Calendar Change

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/certigate#88]
1- Update the course calendar to match the below wireframe
2- Course Calendar shall be filled using both course and course events
![course calendar](https://cloud.githubusercontent.com/assets/8982139/13552772/9c079d76-e378-11e5-972f-1830ac6c4041.png)

**Comment by lebaz20** [comment]
Update calendar view to match visible wireframe
- [x] Update setCanEnroll to detect if course is full

Update instructor calendar view to deal with course event and course
- [x] Update instructorCalendarAction to return course events

Update enrollAction/ leaveAction
- [x] use course event id instead of course

Update moreAction
- [x] remove evaluate link ,view it if user is enrolled in course and event id is passed in url
- [x] validate if course event does not belong to course

Update Course vote action
- [x] set course event in vote entity instead of course -> take event id
- [x] Move exambook back to course
- [x] Add pdf download for outlines

**Comment by babanesma** [comment]
- when you open /courses/calendar you will see a fatal error 
- if you submitted the course evaluation and set it as active , that fatal error will disappear and the course calendar will load
